version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 4444
      POSTGRES_USER: root
      POSTGRES_DB: EMPLOYEES

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

volumes:
  postgres_data: