# Generated by Django 4.2.16 on 2024-11-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_department_name_alter_position_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name_az',
            field=models.CharField(max_length=100, null=True, verbose_name='Department Name'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Department Name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='name_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='surname_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='surname_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='name_az',
            field=models.CharField(max_length=100, null=True, verbose_name='Position Name'),
        ),
        migrations.AddField(
            model_name='position',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Position Name'),
        ),
    ]
