# Generated by Django 4.2.16 on 2024-11-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_department_name_az_department_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='surname_az',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='surname_en',
        ),
    ]
